use crate::services::audio_service::{InputDeviceInfo, InputDeviceListPayload};
use crate::state::{RecordingMode, RecordingOutcomeKind, RecordingPhase, RecordingSnapshot};
use std::fs;
use std::path::{Path, PathBuf};
use ts_rs::{Config, TS};

const GENERATED_HEADER: &str = "// Generated by ts-rs 12.0.1 from Rust IPC DTOs.\n// Regenerate intentionally with:\n// cargo test --manifest-path src-tauri/Cargo.toml --lib ipc_dto_contract_tests::regenerate_checked_in_ipc_bindings -- --ignored\n\n";

fn ts_config() -> Config {
    Config::default().with_large_int("number")
}

fn ipc_bindings_path() -> PathBuf {
    Path::new(env!("CARGO_MANIFEST_DIR")).join("../src/types/generated/ipc.ts")
}

fn checked_in_ipc_bindings() -> String {
    let path = ipc_bindings_path();
    fs::read_to_string(&path).unwrap_or_else(|error| {
        panic!(
            "checked-in IPC bindings are required at {}: {error}",
            path.display()
        )
    })
}

fn normalize_newlines(source: &str) -> String {
    source.replace("\r\n", "\n").replace('\r', "\n")
}

fn render_ipc_bindings() -> String {
    let config = ts_config();
    let declarations = [
        RecordingMode::decl(&config),
        RecordingPhase::decl(&config),
        RecordingOutcomeKind::decl(&config),
        RecordingSnapshot::decl(&config),
        InputDeviceInfo::decl(&config),
        InputDeviceListPayload::decl(&config),
    ]
    .into_iter()
    .map(|declaration| format!("export {declaration}"))
    .collect::<Vec<_>>()
    .join("\n\n");
    format!("{GENERATED_HEADER}{declarations}\n")
}

#[test]
fn checked_in_ipc_bindings_match_real_rust_types() {
    let config = ts_config();
    let checked_in = checked_in_ipc_bindings();
    assert_eq!(
        normalize_newlines(&checked_in),
        normalize_newlines(&render_ipc_bindings()),
        "checked-in IPC bindings drifted from the declarations generated by the Rust DTOs"
    );

    let mode = RecordingMode::decl(&config);
    for variant in ["dictation", "assistant"] {
        assert!(mode.contains(&format!("\"{variant}\"")));
    }

    let phase = RecordingPhase::decl(&config);
    for variant in ["idle", "starting", "recording", "processing", "outcome"] {
        assert!(phase.contains(&format!("\"{variant}\"")));
    }

    let outcome = RecordingOutcomeKind::decl(&config);
    for variant in [
        "too_short",
        "no_speech",
        "asr_error",
        "processing_error",
        "start_error",
    ] {
        assert!(outcome.contains(&format!("\"{variant}\"")));
    }

    let snapshot = RecordingSnapshot::decl(&config);
    for field in [
        "sessionId: number",
        "revision: number",
        "phase: RecordingPhase",
        "mode: RecordingMode",
        "outcome?: RecordingOutcomeKind,",
        "detail?: string,",
    ] {
        assert!(
            snapshot.contains(field),
            "snapshot declaration missing {field}"
        );
    }
    assert!(!snapshot.contains("outcome?: RecordingOutcomeKind | null"));
    assert!(!snapshot.contains("detail?: string | null"));

    let input_devices = InputDeviceListPayload::decl(&config);
    for field in [
        "devices: Array<InputDeviceInfo>",
        "selectedDeviceName: string | null",
    ] {
        assert!(
            input_devices.contains(field),
            "input-device declaration missing {field}"
        );
    }
}

#[test]
#[ignore = "writes the checked-in IPC artifact only during an intentional regeneration"]
fn regenerate_checked_in_ipc_bindings() {
    let path = ipc_bindings_path();
    if let Some(parent) = path.parent() {
        fs::create_dir_all(parent).unwrap();
    }
    fs::write(path, render_ipc_bindings()).unwrap();
}

#[test]
fn ipc_dtos_preserve_serde_names_numbers_nullability_and_unicode() {
    assert_eq!(
        serde_json::to_value([RecordingMode::Dictation, RecordingMode::Assistant,]).unwrap(),
        serde_json::json!(["dictation", "assistant"])
    );
    assert_eq!(
        serde_json::to_value([
            RecordingPhase::Idle,
            RecordingPhase::Starting,
            RecordingPhase::Recording,
            RecordingPhase::Processing,
            RecordingPhase::Outcome,
        ])
        .unwrap(),
        serde_json::json!(["idle", "starting", "recording", "processing", "outcome"])
    );
    assert_eq!(
        serde_json::to_value([
            RecordingOutcomeKind::TooShort,
            RecordingOutcomeKind::NoSpeech,
            RecordingOutcomeKind::AsrError,
            RecordingOutcomeKind::ProcessingError,
            RecordingOutcomeKind::StartError,
        ])
        .unwrap(),
        serde_json::json!([
            "too_short",
            "no_speech",
            "asr_error",
            "processing_error",
            "start_error"
        ])
    );

    let idle = serde_json::to_value(RecordingSnapshot::new(
        u64::MAX,
        u64::MAX - 1,
        RecordingPhase::Idle,
        RecordingMode::Dictation,
    ))
    .unwrap();
    assert_eq!(idle["sessionId"].as_u64(), Some(u64::MAX));
    assert_eq!(idle["revision"].as_u64(), Some(u64::MAX - 1));
    assert!(idle.get("outcome").is_none());
    assert!(idle.get("detail").is_none());

    let outcome = serde_json::to_value(RecordingSnapshot::outcome(
        7,
        8,
        RecordingMode::Assistant,
        RecordingOutcomeKind::AsrError,
        Some("麦克风 🎙️ 不可用"),
    ))
    .unwrap();
    assert_eq!(outcome["sessionId"], serde_json::json!(7));
    assert_eq!(outcome["revision"], serde_json::json!(8));
    assert_eq!(outcome["phase"], serde_json::json!("outcome"));
    assert_eq!(outcome["mode"], serde_json::json!("assistant"));
    assert_eq!(outcome["outcome"], serde_json::json!("asr_error"));
    assert_eq!(outcome["detail"], serde_json::json!("麦克风 🎙️ 不可用"));

    let without_selection = serde_json::to_value(InputDeviceListPayload {
        devices: vec![InputDeviceInfo {
            name: "内置麦克风 🎙️".to_string(),
            is_default: true,
        }],
        selected_device_name: None,
    })
    .unwrap();
    assert_eq!(
        without_selection["devices"][0]["name"],
        serde_json::json!("内置麦克风 🎙️")
    );
    assert_eq!(
        without_selection["devices"][0]["isDefault"],
        serde_json::json!(true)
    );
    assert!(without_selection.get("selectedDeviceName").is_some());
    assert!(without_selection["selectedDeviceName"].is_null());

    let with_selection = serde_json::to_value(InputDeviceListPayload {
        devices: Vec::new(),
        selected_device_name: Some("USB 🎧".to_string()),
    })
    .unwrap();
    assert_eq!(
        with_selection["selectedDeviceName"],
        serde_json::json!("USB 🎧")
    );
}
